# This file was generated by GoReleaser. DO NOT EDIT.
cask "govm" do
  version "0.1.9"

  on_macos do
    sha256 "bf8108d339638be4f32cb7d17d226875d3031893f9e00035b9b750bb040370a4"
    url "https://github.com/smileoniks-ctrl/govm/releases/download/v#{version}/govm_#{version}_Darwin_all.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "2e620027c8f91c070ca31e31af78390d8984fc6d40b8769393e484c0816cf232"
      url "https://github.com/smileoniks-ctrl/govm/releases/download/v#{version}/govm_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "e287517ed58d9d1e7d57bdf40cdadd3841f3236b51c08e3c46b09a732f53e778"
      url "https://github.com/smileoniks-ctrl/govm/releases/download/v#{version}/govm_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "govm"
  desc "GoVM - Go Version Manager"
  homepage "https://github.com/smileoniks-ctrl/govm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "govm"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/govm"]
    end
  end

  # No zap stanza required

end
