# This file was generated by GoReleaser. DO NOT EDIT.
cask "govm" do
  version "0.2.0"

  on_macos do
    sha256 "bf2b4f2b2f09c4be3976c1e0fdac23c96ad57889edf246962e64784206b82cd1"
    url "https://github.com/smileoniks-ctrl/govm/releases/download/v#{version}/govm_#{version}_Darwin_all.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "06bebca505c2143863e8944f42d79ecb5d944f48f595c08a549c2b15b029aeb2"
      url "https://github.com/smileoniks-ctrl/govm/releases/download/v#{version}/govm_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "5bdd47ea2f341efe242c685e3e723d1a64e4a1f5874a2da7362655072d275aba"
      url "https://github.com/smileoniks-ctrl/govm/releases/download/v#{version}/govm_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "govm"
  desc "GoVM - Go Version Manager"
  homepage "https://github.com/smileoniks-ctrl/govm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "govm"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/govm"]
    end
  end

  # No zap stanza required

end
