# This file was generated by GoReleaser. DO NOT EDIT.
cask "govm" do
  version "0.1.5"

  on_macos do
    sha256 "e2d447f86727495bb1226371c0b6b793236afae9c08e62fb9a1344893bed86d6"
    url "https://github.com/smileoniks-ctrl/govm/releases/download/v#{version}/govm_#{version}_Darwin_all.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "2963a2d80d28b640c24f3fe8013786d0b2d32ceecba9996fbb7f773159cad562"
      url "https://github.com/smileoniks-ctrl/govm/releases/download/v#{version}/govm_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "87ebf05bcdeba12e17edc93887c420bafab1a9ea6f59b9a85d5f480bcc9ef6ac"
      url "https://github.com/smileoniks-ctrl/govm/releases/download/v#{version}/govm_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "govm"
  desc "GoVM - Go Version Manager"
  homepage "https://github.com/smileoniks-ctrl/govm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "govm"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/govm"]
    end
  end

  # No zap stanza required

end
