# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Govm < Formula
  desc "GoVM - Go Version Manager"
  homepage "https://github.com/smileoniks-ctrl/govm"
  version "0.1.0"
  license "MIT"

  on_macos do
    url "https://github.com/smileoniks-ctrl/govm/releases/download/v0.1.0/govm_0.1.0_Darwin_all.tar.gz"
    sha256 "46fe2b846992726c0f213d39eed6724b5aa824858a3b5850068e82f24021c792"

    define_method(:install) do
      bin.install "govm"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/smileoniks-ctrl/govm/releases/download/v0.1.0/govm_0.1.0_Linux_x86_64.tar.gz"
      sha256 "607b50c7774d3c52008d604e95a62f6e33c3c022ad053791e0a8db128c88c8dd"
      define_method(:install) do
        bin.install "govm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/smileoniks-ctrl/govm/releases/download/v0.1.0/govm_0.1.0_Linux_arm64.tar.gz"
      sha256 "adbdbc21f66eb8f59219779902c5a8f329e2513d162001bc7f9736ebee67666d"
      define_method(:install) do
        bin.install "govm"
      end
    end
  end
end
